### ISSUE TITLE
请问有例子吗

### ISSUE THREAD

**Issue by notbucai** [dengdai1993/react-native-tencent-cos-v5#1]
请问有示例吗

**Comment by dengdai1993** [comment]
let COS = require('../utils/cos-react-native-sdk-v5.js');
initCos() {
        this.cos = new COS({
            getAuthorization: function (options, callback) {
                let body = "Method=" + options.Method + "&Key=" + options.Key
                fetch(constants.host + constants.workspace + 'api/txcos/sts.php', {
                    method: 'GET',
                }).then((response) => response.json()).then(
                    (responseJson) => {
                        // alert(JSON.stringify(responseJson))
                        let data = responseJson.data
                        callback({
                            TmpSecretId: data.credentials && data.credentials.tmpSecretId,
                            TmpSecretKey: data.credentials && data.credentials.tmpSecretKey,
                            XCosSecurityToken: data.credentials && data.credentials.sessionToken,
                            ExpiredTime: data.expiredTime,
                        });
                    })
                    .catch((error) => {
                        alert(error);
                    });
            }
        });
    }

this.cos.postObject({
            Bucket: this.Bucket,
            Region: this.Region,
            Key: key,
            FilePath: result.uri
        }, function (err, response) {
            if (err) {
                alert("上传失败")
                return;
            }
            result.remoteUrl = key;
            
        });

**Comment by dengdai1993** [comment]
> 请问有示例吗


let COS = require('../utils/cos-react-native-sdk-v5.js');
initCos() {
        this.cos = new COS({
            getAuthorization: function (options, callback) {
                let body = "Method=" + options.Method + "&Key=" + options.Key
                fetch(constants.host + constants.workspace + 'api/txcos/sts.php', {
                    method: 'GET',
                }).then((response) => response.json()).then(
                    (responseJson) => {
                        // alert(JSON.stringify(responseJson))
                        let data = responseJson.data
                        callback({
                            TmpSecretId: data.credentials && data.credentials.tmpSecretId,
                            TmpSecretKey: data.credentials && data.credentials.tmpSecretKey,
                            XCosSecurityToken: data.credentials && data.credentials.sessionToken,
                            ExpiredTime: data.expiredTime,
                        });
                    })
                    .catch((error) => {
                        alert(error);
                    });
            }
        });
    }

this.cos.postObject({
            Bucket: this.Bucket,
            Region: this.Region,
            Key: key,
            FilePath: result.uri
        }, function (err, response) {
            if (err) {
                alert("上传失败")
                return;
            }
            result.remoteUrl = key;
            
        });

**Comment by dengdai1993** [comment]
没有加上传进度，只会回调成功失败

**Comment by notbucai** [comment]
> 没有加上传进度，只会回调成功失败

https://github.com/tencentyun/cos-xml-react-native
 
大哥这个库用过吗，他小文件打包后只有进度没有回调

**Comment by dengdai1993** [comment]
没。。。就是因为没找到好用的，才自己改了下本来是个给js用的库

**Comment by notbucai** [comment]
> 没。。。就是因为没找到好用的，才自己改了下本来是个给js用的库

没有进度是因为 rn `XMLHttpRequest` 的问题吗

**Comment by dengdai1993** [comment]
因为我懒得加了T_T

**Comment by notbucai** [comment]
> 因为我懒得加了T_T

能给思路嘛，嘻嘻嘻

**Comment by dengdai1993** [comment]
![image](https://user-images.githubusercontent.com/12017760/102715153-4cade500-430e-11eb-941e-4232fe9d5daa.png)
我记得我替换的这里，为了省事直接换成了fetch

**Comment by dengdai1993** [comment]
![image](https://user-images.githubusercontent.com/12017760/102715169-72d38500-430e-11eb-941d-4021d6c17839.png)

**Comment by dengdai1993** [comment]
if (filePath.startsWith('data')) {
            let file = dataURLtoFile(filePath);
            cosFormData.append('file', file);
            console.log(JSON.stringify("cosFormData:" + file))
            fetch(url,{
                method :"POST",
                body: cosFormData,
                headers: {
                    "Content-Type": "multipart/form-data; boundary="
                }
            }).then((response) => {
                // alert("上传成功" + response);
                console.log("上传成功2" + response);
                // callback(true);
                callback(null, {statusCode: 200, headers: response.header}, response.data);
            }).catch((error) => {
                // alert("上传失败" + error);
                console.log("上传失败2" + error);
                callback(false);
            });
        } else {
            let file = {uri: filePath, type: 'multipart/form-data', name: 'image.jpeg'};
            cosFormData.append('file', file);
            console.log(JSON.stringify(cosFormData))
            fetch(url,{
                method :"POST",
                body: cosFormData,
                headers: {
                    "Content-Type": "multipart/form-data"
                }
            }).then((response) => {
                console.log("上传成功1" + response);
                callback(null, {statusCode: 200, headers: response.header}, response.data);
            }).catch((error) => {
                console.log("上传失败1" + error);
                callback(false);
            });
        }

**Comment by dengdai1993** [comment]
我替换了这里，大概是第2716行，为了省事换成了fetch传的，所以没进度

**Comment by notbucai** [comment]
爱了爱了，我先试试，可能后面还得麻烦你

**Comment by dengdai1993** [comment]
我是做android和ios原生开发的，对js其实不是很熟。。。你先试试吧

**Comment by notbucai** [comment]
谢谢，已经搞定了
